### ISSUE TITLE
FYI - tar files created on OSX give wierd messages on Linux

### ISSUE THREAD

**Issue by tseemann** [lh3/fermikit#1]
Heng, just in case anyone contacts you about it, untarring on Linux will give this message:

```
% tar jxvf fermikit.tar.bz2
tar: Ignoring unknown extended header keyword `SCHILY.dev'
tar: Ignoring unknown extended header keyword `SCHILY.ino'
tar: Ignoring unknown extended header keyword `SCHILY.nlink'
<snip>
```

Apparently it is harmless: http://lifeonubuntu.com/tar-errors-ignoring-unknown-extended-header-keyword/

**Comment by lh3** [comment]
Thanks a lot. I will tar the source code in linux.
