### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by tmozgach** [lh3/fermikit#16]
What is a the license? Please consider adding a LICENSE file to the GitHub repository.
For instructions, see https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by petermchale** [comment]
I am developing a piece of software based upon fermikit. It would be great to confirm that fermikit has been licensed for others to use, e.g., under the MIT license. Thanks!

**Comment by lh3** [comment]
LICENSE file added. Thanks for the reminder.
