### ISSUE TITLE
GFA output?

### ISSUE THREAD

**Issue by ekg** [lh3/fermikit#2]
Could the cleaned assembly graphs be output in GFA? What would need to be written?

**Comment by lh3** [comment]
I didn't have this need, but as now you are asking... [mag2gfa](https://github.com/lh3/mag2gfa). Not carefully tested.

**Comment by ekg** [comment]
Amazing, thanks @lh3!

**Comment by readmanchiu** [comment]
In the sam sorting step when I ran fermi.kit/run-calling:

$root/htsbox samview -Sl0 $prefix.unsrt.sam.gz | samtools sort -m20G - $prefix.srt

Does it generate a single bam for each sequence?  it generated so many bam's _.srt._.bam that I have to kill the process and remove all the tiny bams.

**Comment by lh3** [comment]
What samtools version do you have? I guess it is very old?

**Comment by lh3** [comment]
I guess what is happening to you is that you are using a very old samtools that does not support "-m20G". Anyway, I was wrong to say "fermikit" only depends on zlib. For variant calling, it also calls "samtools" for sorting. Probably I should write a quick internal sort to get rid of the samtools dependency. Thanks for the report.

**Comment by readmanchiu** [comment]
yes, I figured it's samtools version being old.  I'll try a later version
after removing all intermediate bams.  Thanks for your quick reply.
