### ISSUE TITLE
fermikit-0.12.tar.bz2 has weird Mac OS extensions

### ISSUE THREAD

**Issue by sjackman** [lh3/fermikit#4]
Extracting `fermikit-0.12.tar.bz2` on Linux causes tar to fail with a non-zero exit status due to non-standard BSD extensions in the tar file.

```
$ tar xf fermikit-0.12.tar.bz2 
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
```

See [Fix Tar Errors on OS X](http://lee.greens.io/blog/2014/05/06/fix-tar-errors-on-os-x/) and [superuser](http://superuser.com/questions/318809/linux-os-x-tar-incompatibility-tarballs-created-on-os-x-give-errors-when-unt).

The fix is to set set an environment variable before creating the tar file on Mac OS.

``` sh
export COPYFILE_DISABLE=true
```

**Comment by lh3** [comment]
I have updated fermikit-0.12.tar.bz2. It should be fine now.

**Comment by sjackman** [comment]
Thanks, Heng.
