### ISSUE TITLE
pipeline questions

### ISSUE THREAD

**Issue by mcshane** [lh3/fermikit#5]
Hi Heng,

Few quick questions. Starting from BAM,
- should duplicates be removed when converting to fastq?
- seeing as you are not using pair information, does it matter if reads in the input fastq are in the order they come from the sorted BAM file? i.e. can I skip a `bamshuf` step?
- you have `htsbox abreak` taking unsorted SAM as input. Is unsorted required, or can it be sorted?

Cheers,
Shane

**Comment by lh3** [comment]
> should duplicates be removed when converting to fastq?

It is not necessary to remove duplicates. Identical reads after error correction will be effectively collapsed anyway.

> seeing as you are not using pair information, does it matter if reads in the input fastq are in the order they come from the sorted BAM file? i.e. can I skip a bamshuf step?

You can skip the `bamshuf` step. Just use `bam2fq` like:

``` sh
fermi.kit/fermi2.pl unitig "samtools bam2fq in.bam"
```

When the last argument is not a file, the perl script will take it as a command line and read data from its STDOUT.

> you have htsbox abreak taking unsorted SAM as input. Is unsorted required, or can it be sorted?

The input SAM has to be name grouped.

**Comment by mcshane** [comment]
Thanks Heng.

**Comment by lh3** [comment]
After a second thought, dedup before error correction might be better in theory because there will be fewer consistent PCR errors which may hurt error correction. Nonetheless, in practice, probably this doesn't matter. For the false positives I have seen, PCR duplicates are not an obvious driver.
